Repository Talk-Spark/talk-spark-frontend, pull requests merged in 2024-12, with the labels that each got.

#25 [Feat/#21] 온보딩 퍼블리싱
  package.json
  pnpm-lock.yaml
  public/Image/onBoarding/kakaoImage.svg
  public/Image/onBoarding/landingImage.svg
  public/Image/onBoarding/loginImage.svg
  src/app/(onBoarding)/creating-card/page.tsx
  src/app/(onBoarding)/creating-card/result/creating-card.json
  src/app/(onBoarding)/creating-card/result/page.tsx
  src/app/(onBoarding)/landing/page.tsx
  src/app/(onBoarding)/login/page.tsx
  src/components/Headers/Header.tsx
  src/components/Headers/HeaderWrapper.tsx
  src/components/creating-card/InputField.tsx
  src/components/creating-card/Step1.tsx
  src/components/creating-card/Step2.tsx
  src/components/creating-card/Step3.tsx
  src/components/creating-card/Step4.tsx
  tailwind.config.ts
Labels: 🌿 REFACTORING, 🛠️ FEATURE, 🧑🏻‍💻 동욱

#36 [Feat/#35] API 인스턴스 생성
  src/apis/index.ts
  src/app/dashboard/page.tsx
Labels: 📟 API

#32 [Feat/#30] 명함 보관함 퍼블리싱
  package.json
  pnpm-lock.yaml
  public/entry/scanner.svg
  public/nameCard/Qr.svg
  public/nameCard/Star.svg
  public/nameCard/blueCardBack.svg
  public/nameCard/blueStorageGraphic.svg
  public/nameCard/camera.svg
  public/nameCard/leftArrow.svg
  public/nameCard/mintStorageGraphic.svg
  public/nameCard/pinkStar.svg
  public/nameCard/pinkStoragePink.svg
  public/nameCard/rightArrow.svg
  public/nameCard/yellowStorageGraphic.svg
  public/storageNameCard/arrowBt.svg
  src/app/card/detail/[name]/page.tsx
  src/app/card/page.tsx
  src/app/entry/camera/page.tsx
  src/app/layout.tsx
  src/app/team/[id]/page.tsx
  src/components/Headers/HeaderWrapper.tsx
  src/components/QrCode/QrCode.tsx
  src/components/QrCode/QrCodeDown.tsx
  src/components/QrCode/ReadCode.tsx
  src/components/SearchInput.tsx
  src/components/Storage/Arrow.tsx
  src/components/Storage/Logout.tsx
  src/components/Storage/MyCard.tsx
  src/components/Storage/QrCard.tsx
  src/components/Storage/SearchAndGetCard.tsx
  src/components/Storage/Sorting.tsx
  src/components/Storage/TeamBox.tsx
  src/components/Storage/ToggleBar.tsx
  src/components/StorageNameCard.tsx
  src/components/entry/Camera.tsx
  src/components/guest-book/New.tsx
  tailwind.config.ts
Labels: 🛠️ FEATURE, 🧑🏻‍💻 정인

#33 [Feat/#27] 메인홈 퍼블리싱
  public/Image/home/backgroundImage.svg
  public/Image/home/blueBackgroundImage.svg
  public/Image/home/chat_1.svg
  public/Image/home/chat_2.svg
  public/Image/home/chat_3.svg
  public/Image/home/creatingRoomImage.svg
  public/Image/home/enteringRoomImage.svg
  public/Image/home/mintBackgroundImage.svg
  public/Image/home/pinkBackgroundImage.svg
  public/Image/home/yellowBackgroundImage.svg
  src/app/home/page.tsx
  src/components/home/CardMatching.tsx
  src/components/home/MyCard.tsx
  src/components/home/Storage.tsx
  src/components/home/card/CardStorage.tsx
  src/components/home/card/NameCardComponent.tsx
  src/components/home/guest/BookStorage.tsx
  src/components/home/guest/GuestBookComponent.tsx
Labels: 🛠️ FEATURE, 🧑🏻‍💻 동욱

#38 [Feat/#31] 방명록 보관함 퍼블리싱
  package.json
  pnpm-lock.yaml
  public/guest-book/checkBox.svg
  public/guest-book/fullCheckBox.svg
  public/guest-book/new.svg
  public/guest-book/sendIcon.svg
  src/app/globals.css
  src/app/guest-book/[id]/page.tsx
  src/app/guest-book/page.tsx
  src/components/Headers/HeaderWrapper.tsx
  src/components/Storage/MyCard.tsx
  src/components/Storage/SearchAndGetCard.tsx
  src/components/Storage/TeamBox.tsx
  src/components/StorageNameCard.tsx
  src/components/guest-book/CommentInput.tsx
  src/components/guest-book/FixedComment.tsx
  src/components/guest-book/MyTalk.tsx
  src/components/guest-book/YourTalk.tsx
  src/components/home/MyCard.tsx
  tsconfig.json
Labels: 🛠️ FEATURE, 🧑🏻‍💻 정인, 🎨 DESIGN

#48 [Feat/#37] 카카오 로그인
  src/app/(onBoarding)/login/page.tsx
  src/app/auth/page.tsx
Labels: 🧑🏻‍💻 동욱, 📟 API

#34 [Feat/#28] 방 생성 퍼블리싱
  public/Image/creating-room/difficult_default.svg
  public/Image/creating-room/difficult_pressed.svg
  public/Image/creating-room/easy_default.svg
  public/Image/creating-room/easy_pressed.svg
  public/Image/creating-room/normal_default.svg
  public/Image/creating-room/normal_pressed.svg
  public/Image/creating-room/random_default.svg
  public/Image/creating-room/random_pressed.svg
  src/app/creating-room/page.tsx
  src/app/creating-room/result/page.tsx
  src/components/Headers/HeaderWrapper.tsx
  src/components/creating-card/InputField.tsx
  src/components/creating-room/Step1.tsx
  src/components/creating-room/Step2.tsx
  src/components/creating-room/Step3.tsx
Labels: 🛠️ FEATURE, 🧑🏻‍💻 동욱

#46 [Feat/#45] 명함 생성 api 연결
  src/app/(onBoarding)/creating-card/page.tsx
  src/components/creating-card/Step1.tsx
  src/components/creating-card/Step3.tsx
  src/components/creating-card/Step4.tsx
Labels: 🧑🏻‍💻 동욱, 📟 API

#49 [Feat/#40] 명함 보관함 api
  public/Image/entry/arrowLeft.svg
  public/Image/entry/camera.svg
  public/Image/entry/scanner.svg
  public/Image/entry/search.svg
  public/Image/entry/searchGraphic.svg
  public/Image/entry/starBlue.svg
  public/Image/entry/starMint.svg
  public/Image/entry/starPink.svg
  public/Image/entry/starYellow.svg
  public/countdown_white.json
  src/apis/index.ts
  src/app/card/detail/[id]/page.tsx
  src/app/card/page.tsx
  src/app/guest-book/page.tsx
  src/components/QrCode/ReadCode.tsx
  src/components/SearchInput.tsx
  src/components/Storage/Arrow.tsx
  src/components/Storage/MyCard.tsx
  src/components/Storage/SearchAndGetCard.tsx
  src/components/Storage/TeamBox.tsx
  src/components/StorageNameCard.tsx
  src/components/entry/FindRoom.tsx
  src/components/entry/Start.tsx
  src/components/entry/TeamRoomList.tsx
Labels: 🧑🏻‍💻 정인, 📟 API

#53 [Feat] 임시
  src/app/creating-room/result/page.tsx
  src/components/creating-card/Step4.tsx
  src/components/creating-room/Step3.tsx
  src/components/home/MyCard.tsx
  src/components/home/Storage.tsx
Labels: 🛠️ FEATURE, 🧑🏻‍💻 동욱

#56 [Fix/#55] 색상 대문자 수정
  src/app/card/detail/[id]/page.tsx
  src/app/guest-book/[id]/page.tsx
  src/components/ProfileImage.tsx
  src/components/QrCode/QrCodeDown.tsx
  src/components/Storage/MyCard.tsx
  src/components/Storage/QrCard.tsx
  src/components/StorageNameCard.tsx
  src/components/creating-card/Step4.tsx
  src/components/guest-book/FixedComment.tsx
  src/components/guest-book/MyTalk.tsx
  src/components/home/MyCard.tsx
  src/components/home/card/CardStorage.tsx
Labels: 🛠️ FIX, 🧑🏻‍💻 정인

#59 [Fix] GREEN -> MINT
  src/app/card/detail/[id]/page.tsx
  src/app/team/[id]/page.tsx
  src/components/ProfileImage.tsx
  src/components/QrCode/QrCodeDown.tsx
  src/components/Storage/MyCard.tsx
  src/components/Storage/QrCard.tsx
  src/components/StorageNameCard.tsx
  src/components/guest-book/FixedComment.tsx
  src/components/home/MyCard.tsx
  src/components/home/card/CardStorage.tsx
Labels: 🛠️ FIX

#57 [Feat/#47] 메인홈 api 연결 / 방 생성 중복검사 추가
  package.json
  pnpm-lock.yaml
  src/app/auth/page.tsx
  src/app/creating-room/result/page.tsx
  src/components/creating-card/InputField.tsx
  src/components/creating-card/Step4.tsx
  src/components/creating-room/Step1.tsx
  src/components/home/MyCard.tsx
  src/components/home/Storage.tsx
  src/components/home/card/CardStorage.tsx
  src/components/home/card/NameCardComponent.tsx
  src/components/home/guest/BookStorage.tsx
  src/components/home/guest/GuestBookComponent.tsx
Labels: 🛠️ FEATURE, 🧑🏻‍💻 동욱, 📟 API

#68 [Fix/#61] 수정 사항 FIx
  src/app/card/detail/[id]/page.tsx
  src/app/card/page.tsx
  src/app/guest-book/[id]/page.tsx
  src/app/guest-book/page.tsx
  src/components/Headers/HeaderWrapper.tsx
  src/components/QrCode/ReadCode.tsx
  src/components/Storage/SearchAndGetCard.tsx
  src/components/Storage/TeamBox.tsx
  src/components/Storage/card/CardBotttom.tsx
  src/components/Storage/card/CardTop.tsx
  src/components/Storage/card/MyCard.tsx
  src/components/StorageNameCard.tsx
  src/components/guest-book/YourTalk.tsx
Labels: 🧑🏻‍💻 정인, 📟 API

#72 [Fix/#70]
  src/app/(flow)/flow/page.tsx
  src/app/card/detail/[id]/page.tsx
  src/app/card/page.tsx
  src/app/creating-room/page.tsx
  src/app/creating-room/result/page.tsx
  src/app/entry/page.tsx
  src/app/team/[id]/page.tsx
  src/components/Headers/HeaderWrapper.tsx
  src/components/ParentComponet.tsx
  src/components/ProfileImage.tsx
  src/components/Storage/QrCard.tsx
  src/components/Storage/SearchAndGetCard.tsx
  src/components/Storage/TeamBox.tsx
  src/components/Storage/card/CardTop.tsx
  src/components/Storage/card/QrCard.tsx
  src/components/StorageNameCard.tsx
  src/components/flow/AfterSelect.tsx
  src/components/flow/BeforeSelect.tsx
  src/components/home/Storage.tsx
  src/components/home/card/CardStorage.tsx
Labels: 🛠️ FIX, 🧑🏻‍💻 정인
