Repository Talk-Spark/talk-spark-frontend, pull requests merged in 2024-11, with the labels that each got.

#4 [Design] Global styling
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Header.tsx
  tailwind.config.ts
Labels: ⚙️ ENVIRONMENT, 🧑🏻‍💻 동욱, 🎨 DESIGN

#6 [Feat/#5] 공통 컴포넌트 - 버튼 구현
  src/app/page.tsx
  src/components/common/Button.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 🛠️ FEATURE, 🧑🏻‍💻 준혁

#15 [Feat/#12] 공통 컴포넌트 - 헤더 구현
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Header.tsx
  src/components/Headers/Header.tsx
  src/components/Headers/HeaderWrapper.tsx
  src/components/Headers/icon.svg
Labels: 🛠️ FEATURE, 🧑🏻‍💻 동욱, 🎨 DESIGN

#8 [Feat/#7] 공통 컴포넌트 - 프로필 이미지 구현
  public/nameCard/major.svg
  public/profile/blue.svg
  public/profile/blueCrown.svg
  public/profile/green.svg
  public/profile/greenCrown.svg
  public/profile/pink.svg
  public/profile/pinkCrown.svg
  public/profile/yellow.svg
  public/profile/yellowCrown.svg
  src/components/ProfileImage.tsx
  src/components/StorageNameCard.tsx
  tailwind.config.ts
Labels: 🛠️ FEATURE, 🧑🏻‍💻 정인, 🎨 DESIGN

#11 [Feat/#10] 공통 컴포넌트 - 명함 맞추기에서의 명함
  src/app/page.tsx
  src/components/NameCard.tsx
  src/components/ParentComponet.tsx
Labels: 🛠️ FEATURE, 🧑🏻‍💻 정인, 🎨 DESIGN

#17 [Feat] 명함보관함에서의 명함 공통 컴포넌트 구현
  public/storageNameCard/BlueCard.svg
  public/storageNameCard/MintCard.svg
  public/storageNameCard/Pinkcard.svg
  public/storageNameCard/YellowCard.svg
  public/storageNameCard/blackDown.svg
  public/storageNameCard/blackMajorIcon.svg
  public/storageNameCard/blackPencil.svg
  public/storageNameCard/blueGraphics.svg
  public/storageNameCard/blueMajorIcon.svg
  public/storageNameCard/down.svg
  public/storageNameCard/greenGraphics.svg
  public/storageNameCard/pencil.svg
  public/storageNameCard/pinkGraphics.svg
  public/storageNameCard/pinkMajorIcon.svg
  public/storageNameCard/yellowGraphics.svg
  src/components/StorageNameCard.tsx
  tailwind.config.ts
Labels: 🛠️ FEATURE, 🧑🏻‍💻 정인, 🎨 DESIGN

#24 [Refactor/#23] 헤더 수정
  src/components/Headers/Header.tsx
  src/components/Headers/HeaderWrapper.tsx
Labels: 🌿 REFACTORING, 🧑🏻‍💻 동욱, 🎨 DESIGN
