Repository Talk-Spark/talk-spark-frontend, pull requests merged in 2025-01, with the labels that each got.

#75 [Feat/#73] 명함 이미지 저장 오류 수정
  package.json
  pnpm-lock.yaml
  src/components/Storage/card/CardTop.tsx
  src/components/StorageNameCard.tsx
Labels: 🛠️ FIX, 🧑🏻‍💻 정인, 🎨 DESIGN

#78 [Feat/#74] 보관함 즐겨찾기 PUT / 퍼블리싱 수정
  src/app/auth/page.tsx
  src/app/card/detail/[id]/page.tsx
  src/app/card/page.tsx
  src/app/guest-book/page.tsx
  src/components/Storage/SearchAndGetCard.tsx
  src/components/Storage/TeamBox.tsx
  src/components/Storage/ToggleBar.tsx
  src/components/Storage/card/CardTop.tsx
  src/components/common/Modal.tsx
  src/components/common/PageTransition.tsx
  src/components/home/CardMatching.tsx
  src/components/home/MyCard.tsx
  src/components/home/Storage.tsx
Labels: 🛠️ FIX, 🧑🏻‍💻 정인, 🎨 DESIGN

#82 [Feat/#81] 카카오톡 공유하기 기능 추가
  src/app/creating-room/result/page.tsx
  src/app/layout.tsx
  src/types/global.d.ts
Labels: 🛠️ FEATURE, 🧑🏻‍💻 동욱

#83 [Fix] svg 화질 저하 이슈 해결
  public/Image/creating-room/difficult_default.png
  public/Image/creating-room/difficult_default.svg
  public/Image/creating-room/difficult_pressed.png
  public/Image/creating-room/difficult_pressed.svg
  public/Image/creating-room/easy_default.png
  public/Image/creating-room/easy_default.svg
  public/Image/creating-room/easy_pressed.png
  public/Image/creating-room/easy_pressed.svg
  public/Image/creating-room/normal_default.png
  public/Image/creating-room/normal_default.svg
  public/Image/creating-room/normal_pressed.png
  public/Image/creating-room/normal_pressed.svg
  public/Image/creating-room/random_default.png
  public/Image/creating-room/random_default.svg
  public/Image/creating-room/random_pressed.png
  public/Image/creating-room/random_pressed.svg
  public/Image/home/creatingRoomImage.png
  public/Image/home/enteringRoomImage.png
  src/components/creating-room/Step3.tsx
  src/components/home/CardMatching.tsx
Labels: 🛠️ FIX, 🧑🏻‍💻 동욱

#86 [Feat] 초기 화면 분기처리
  src/app/page.tsx
Labels: 🌿 REFACTORING, 🛠️ FEATURE, 🧑🏻‍💻 동욱, 📟 API

#87 [Feat/#84] 방명록 오류 수정
  public/Image/home/defultPink.svg
  public/loading/loadingColor.gif
  src/app/(flow)/all-cards/page.tsx
  src/app/(flow)/flow/page.tsx
  src/app/card/page.tsx
  src/app/entry/page.tsx
  src/app/guest-book/[id]/page.tsx
  src/app/guest-book/page.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/team/[id]/page.tsx
  src/components/Headers/Header.tsx
  src/components/NameCard.tsx
  src/components/Router/AnimationProvider.tsx
  src/components/Router/ExtendedLink.tsx
  src/components/Router/RouterWrapperProvider.tsx
  src/components/Router/template.tsx
  src/components/SearchInput.tsx
  src/components/Storage/SearchAndGetCard.tsx
  src/components/Storage/TeamBox.tsx
  src/components/Storage/card/QrCard.tsx
  src/components/creating-room/Step3.tsx
  src/components/entry/TeamRoomList.tsx
  src/components/flow/AfterSelect.tsx
  src/components/guest-book/CommentInput.tsx
  src/components/guest-book/FixedComment.tsx
  src/components/guest-book/MyTalk.tsx
  src/components/guest-book/YourTalk.tsx
  src/components/home/CardMatching.tsx
  src/components/home/MyCard.tsx
  src/components/home/Storage.tsx
  src/components/home/card/CardStorage.tsx
  src/components/home/guest/BookStorage.tsx
  src/contexts/RouterWrapperContext.tsx
Labels: 🧑🏻‍💻 정인, 📟 API

#90 [Feat/#89] 3차 Qa 반영
  .github/workflows/buildTest2.yml
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/guest-book/newIcon.svg
  src/app/(flow)/all-cards/page.tsx
  src/app/(flow)/flow/page.tsx
  src/app/entry/page.tsx
  src/app/guest-book/[id]/page.tsx
  src/app/guest-book/page.tsx
  src/app/page.tsx
  src/app/team/[id]/page.tsx
  src/components/QrCode/ReadCode.tsx
  src/components/SearchInput.tsx
  src/components/Storage/SearchAndGetCard.tsx
  src/components/Storage/card/QrCard.tsx
  src/components/StorageNameCard.tsx
  src/components/creating-room/Step3.tsx
  src/components/entry/Start.tsx
  src/components/entry/TeamRoomList.tsx
  src/components/flow/AfterSelect.tsx
  src/components/game-end/BarGraph.tsx
  src/components/guest-book/CommentInput.tsx
  src/components/guest-book/New.tsx
Labels: 🧑🏻‍💻 정인, 📟 API, 🎨 DESIGN
